kind: pipeline
type: docker
name: default

steps:
- name: Run run.sh
  image: debian:stable-slim
  commands:
  - '/drone/src/run.sh'
  volumes:
  - name: repo
    path: /repo

volumes:
- name: repo
  host:
    path: /tmp/repo