kind: pipeline
type: docker
name: default

steps:
- name: Update fedora repo
  image: debian:stable-slim
  commands:
  - '/drone/src/fedora.sh'
  volumes:
  - name: fedora-repo
    path: /repo
- name: Update debian repo
  image: debian:stable-slim
  commands:
  - '/drone/src/debian.sh'
  volumes:
  - name: debian-bookworm-repo
    path: /repo

volumes:
- name: fedora-repo
  host:
    path: /mnt/user/big-stuff/files/repos/fedora/x86_64
- name: debian-bookworm-repo
  host:
    path: /mnt/user/big-stuff/files/repos/debian/bookworm/amd64